export const GET_NOTE = 'DocView/GET_NOTE';
export const RESET = 'DocView/RESET';
export const FETCH_NOTE_ERROR = 'DocView/FETCH_NOTE_ERROR';
export const PUT_ACTIVE_NOTE = 'DocView/PUT_ACTIVE_NOTE';
export const UPDATE_ACTIVE_NOTE_HEADER = 'DocView/UPDATE_ACTIVE_NOTE_HEADER';
export const UPDATE_ACTIVE_NOTE_CONTENT = 'DocView/UPDATE_ACTIVE_NOTE_CONTENT';
