export const GET_NOTE = 'GET_NOTE';
export const FETCH_NOTE_ERROR = 'FETCH_NOTE_ERROR';
export const PUT_ACTIVE_NOTE = 'PUT_ACTIVE_NOTE';
export const UPDATE_ACTIVE_NOTE_HEADER = 'UPDATE_ACTIVE_NOTE_HEADER';
export const UPDATE_ACTIVE_NOTE_CONTENT = 'UPDATE_ACTIVE_NOTE_CONTENT';
